from datetime import datetime
from typing import List

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from backend.database.session import get_db
from backend.models.documentation import DocumentationPage
from backend.models.project import Task, TaskStatus
from backend.models.user import User
from backend.routers.auth import get_current_user
from backend.schemas.documentation import (
    DocumentationPageCreate,
    DocumentationPageOut,
    DocumentationPageUpdate,
)
from backend.utils.permissions import check_project_permission, require_project_permission


router = APIRouter(prefix="/documentation", tags=["Documentation"])


def _enum_value(value) -> str:
    if value is None:
        return ""
    if hasattr(value, "value"):
        return str(value.value)
    return str(value)


def _ensure_task_belongs_to_project(db: Session, project_id: int, task_id: int | None) -> Task | None:
    if not task_id:
        return None

    task = db.query(Task).filter(Task.id == task_id, Task.project_id == project_id).first()
    if not task:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Task does not belong to this project.",
        )

    return task


def _task_documentation_title(task: Task) -> str:
    return f"{task.key} - Technical documentation"


def _task_documentation_content(task: Task) -> str:
    subtasks = list(task.subtasks or [])
    comments = list(task.comments or [])

    completed_subtasks = len([item for item in subtasks if item.is_done])
    total_subtasks = len(subtasks)

    latest_comments = comments[-3:] if comments else []

    subtask_lines = "\n".join(
        f"- [{'x' if item.is_done else ' '}] {item.title}"
        for item in subtasks
    ) or "- No subtasks were recorded."

    comment_lines = "\n".join(
        f"- {comment.author_name or 'Team member'}: {comment.body[:220]}"
        for comment in latest_comments
    ) or "- No implementation comments were recorded."

    return f"""# {task.key} - {task.title}

## Technical summary

This page was generated from the completed task **{task.key}**. It captures the implementation context, delivery status, quality signals and follow-up notes for future maintenance.

## Task metadata

- Status: {_enum_value(task.status)}
- Priority: {_enum_value(task.priority)}
- Story points: {task.story_points or 0}
- Assignee: {task.assignee_name or "Unassigned"}
- Due date: {task.due_date.strftime("%Y-%m-%d") if task.due_date else "Not specified"}

## Implementation notes

{task.description or "No detailed description was provided for this task."}

## Acceptance / completion checklist

{subtask_lines}

Progress: {completed_subtasks}/{total_subtasks} subtasks completed.

## Team discussion highlights

{comment_lines}

## Maintenance notes

- Review related audit logs before changing this area again.
- Confirm that permissions and validation rules still match the intended workflow.
- If this task affects UI behavior, verify board, backlog, workload, reports and activity pages after future changes.

## Generated by SDLC Hub

This documentation page was generated automatically from task data. It can be edited manually by the team.
"""


@router.get("/project/{project_id}", response_model=List[DocumentationPageOut])
def list_project_documentation(
    project_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    check_project_permission(db, current_user.id, project_id)

    return (
        db.query(DocumentationPage)
        .filter(DocumentationPage.project_id == project_id)
        .order_by(DocumentationPage.updated_at.desc(), DocumentationPage.id.desc())
        .all()
    )


@router.post("/project/{project_id}", response_model=DocumentationPageOut)
def create_documentation_page(
    project_id: int,
    page_in: DocumentationPageCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    require_project_permission(db, current_user.id, project_id, "TASK_UPDATE")
    _ensure_task_belongs_to_project(db, project_id, page_in.task_id)

    page = DocumentationPage(
        project_id=project_id,
        task_id=page_in.task_id,
        title=page_in.title.strip(),
        content=page_in.content,
        created_by_id=current_user.id,
    )

    db.add(page)
    db.commit()
    db.refresh(page)

    return page


@router.post("/from-task/{task_id}", response_model=DocumentationPageOut)
def generate_documentation_from_task(
    task_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    task = db.query(Task).filter(Task.id == task_id).first()
    if not task:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Task not found.")

    require_project_permission(db, current_user.id, task.project_id, "AI_USE")

    if _enum_value(task.status) != TaskStatus.DONE.value:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Documentation can only be generated after the task is Done.",
        )

    existing_page = (
        db.query(DocumentationPage)
        .filter(DocumentationPage.project_id == task.project_id, DocumentationPage.task_id == task.id)
        .first()
    )

    title = _task_documentation_title(task)
    content = _task_documentation_content(task)

    if existing_page:
        existing_page.title = title
        existing_page.content = content
        existing_page.updated_at = datetime.utcnow()
        page = existing_page
    else:
        page = DocumentationPage(
            project_id=task.project_id,
            task_id=task.id,
            title=title,
            content=content,
            created_by_id=current_user.id,
        )
        db.add(page)

    db.commit()
    db.refresh(page)

    return page


@router.get("/{page_id}", response_model=DocumentationPageOut)
def get_documentation_page(
    page_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    page = db.query(DocumentationPage).filter(DocumentationPage.id == page_id).first()
    if not page:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Documentation page not found.")

    check_project_permission(db, current_user.id, page.project_id)
    return page


@router.put("/{page_id}", response_model=DocumentationPageOut)
def update_documentation_page(
    page_id: int,
    page_in: DocumentationPageUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    page = db.query(DocumentationPage).filter(DocumentationPage.id == page_id).first()
    if not page:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Documentation page not found.")

    require_project_permission(db, current_user.id, page.project_id, "TASK_UPDATE")

    update_data = page_in.model_dump(exclude_unset=True)

    if "task_id" in update_data:
        _ensure_task_belongs_to_project(db, page.project_id, update_data["task_id"])

    if "title" in update_data and update_data["title"] is not None:
        page.title = update_data["title"].strip()

    if "content" in update_data and update_data["content"] is not None:
        page.content = update_data["content"]

    if "task_id" in update_data:
        page.task_id = update_data["task_id"]

    page.updated_at = datetime.utcnow()

    db.commit()
    db.refresh(page)

    return page


@router.delete("/{page_id}")
def delete_documentation_page(
    page_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    page = db.query(DocumentationPage).filter(DocumentationPage.id == page_id).first()
    if not page:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Documentation page not found.")

    require_project_permission(db, current_user.id, page.project_id, "TASK_UPDATE")

    db.delete(page)
    db.commit()

    return {"message": "Documentation page deleted."}
