from datetime import datetime

from sqlalchemy.orm import Session

from backend.models.documentation import DocumentationPage
from backend.models.project import Task


def enum_value(value) -> str:
    if value is None:
        return ""
    if hasattr(value, "value"):
        return str(value.value)
    return str(value)


def task_documentation_title(task: Task) -> str:
    return f"{task.key} - Technical documentation"


def task_documentation_content(task: Task) -> str:
    subtasks = list(task.subtasks or [])
    comments = list(task.comments or [])

    completed_subtasks = len([item for item in subtasks if item.is_done])
    total_subtasks = len(subtasks)
    latest_comments = comments[-3:] if comments else []

    subtask_lines = "\n".join(
        f"- [{'x' if item.is_done else ' '}] {item.title}"
        for item in subtasks
    ) or "- No subtasks were recorded."

    comment_lines = "\n".join(
        f"- {comment.author_name or 'Team member'}: {comment.body[:220]}"
        for comment in latest_comments
    ) or "- No implementation comments were recorded."

    return f"""# {task.key} - {task.title}

## Technical summary

This page was generated from the completed task **{task.key}**. It captures the implementation context, delivery status, quality signals and follow-up notes for future maintenance.

## Task metadata

- Status: {enum_value(task.status)}
- Priority: {enum_value(task.priority)}
- Story points: {task.story_points or 0}
- Assignee: {task.assignee_name or "Unassigned"}
- Due date: {task.due_date.strftime("%Y-%m-%d") if task.due_date else "Not specified"}

## Implementation notes

{task.description or "No detailed description was provided for this task."}

## Acceptance / completion checklist

{subtask_lines}

Progress: {completed_subtasks}/{total_subtasks} subtasks completed.

## Team discussion highlights

{comment_lines}

## Maintenance notes

- Review related audit logs before changing this area again.
- Confirm that permissions and validation rules still match the intended workflow.
- If this task affects UI behavior, verify board, backlog, workload, reports and activity pages after future changes.

## Generated by SDLC Hub

This documentation page was generated automatically from task data. It can be edited manually by the team.
"""


def upsert_task_documentation_page(
    db: Session,
    task: Task,
    created_by_id: int | None = None,
) -> DocumentationPage:
    existing_page = (
        db.query(DocumentationPage)
        .filter(DocumentationPage.project_id == task.project_id, DocumentationPage.task_id == task.id)
        .first()
    )

    title = task_documentation_title(task)
    content = task_documentation_content(task)

    if existing_page:
        existing_page.title = title
        existing_page.content = content
        existing_page.updated_at = datetime.utcnow()
        page = existing_page
    else:
        page = DocumentationPage(
            project_id=task.project_id,
            task_id=task.id,
            title=title,
            content=content,
            created_by_id=created_by_id,
        )
        db.add(page)

    db.flush()
    return page
