"use client";

import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { BadgeCheck, CheckCircle2, Gauge, Loader2, Plus, Sparkles, Users } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { UserAvatar } from "@/components/user-avatar";

// Asigură-te că generateTaskDescription este exportată din services/task
import {
  createTask,
  estimateTaskStoryPoints,
  generateTaskDescription,
  refineTaskSpec,
  StoryPointEstimate,
  Task,
  TaskPriority,
  RefinedTaskSpec,
} from "@/services/task";
import { getProjectMembers, getProjectTeams, ProjectMember, ProjectTeam } from "@/services/project";

// Schema de validare
const formSchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
  priority: z.nativeEnum(TaskPriority),
  story_points: z.string().optional(),
  due_date: z.string().optional(),
  assignee_id: z.string().optional(),
  team_id: z.string().optional(),
});

interface CreateTaskDialogProps {
  projectId: number;
  sprintId?: number | null;
  methodology?: string;
  onTaskCreated: (task: Task) => void;
}

export function CreateTaskDialog({ projectId, sprintId, methodology, onTaskCreated }: CreateTaskDialogProps) {
  const [open, setOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  
  // State nou pentru loading AI
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [isEstimateLoading, setIsEstimateLoading] = useState(false);
  const [lastEstimate, setLastEstimate] = useState<StoryPointEstimate | null>(null);
  const [lastRefinedSpec, setLastRefinedSpec] = useState<RefinedTaskSpec | null>(null);
  const [createAiSubtasks, setCreateAiSubtasks] = useState(true);
  
  // State pentru membrii echipei
  const [members, setMembers] = useState<ProjectMember[]>([]);
  const [teams, setTeams] = useState<ProjectTeam[]>([]);
  const [loadingMembers, setLoadingMembers] = useState(false);
  const supportsStoryPoints = methodology !== "KANBAN";

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: "",
      description: "",
      priority: TaskPriority.MEDIUM,
      story_points: "",
      due_date: "",
      assignee_id: "unassigned",
      team_id: "none",
    },
  });

  // Încărcăm membrii când se deschide dialogul
  useEffect(() => {
    if (open && projectId) {
        const fetchMembers = async () => {
            setLoadingMembers(true);
            try {
                const [memberData, teamData] = await Promise.all([
                  getProjectMembers(projectId),
                  getProjectTeams(projectId),
                ]);
                setMembers(memberData);
                setTeams(teamData);
            } catch (error) {
                console.error("Failed to load members", error);
                toast.error("Could not load team members");
            } finally {
                setLoadingMembers(false);
            }
        };
        fetchMembers();
    }
  }, [open, projectId]);

  // Funcția care apelează AI-ul
  const handleGenerateAI = async () => {
    const title = form.getValues("title");
    const priority = form.getValues("priority");

    if (!title || title.length < 3) {
        toast.warning("Please enter a valid task title first so the AI has context!");
        return;
    }

    setIsAiLoading(true);
    try {
        // Apel către serviciul definit în services/task.ts
        const aiDescription = await generateTaskDescription(title, priority, projectId);
        
        // Actualizăm câmpul description
        form.setValue("description", aiDescription, { 
            shouldValidate: true, 
            shouldDirty: true 
        });
        toast.success("Description generated by AI!");
    } catch (error) {
        console.error("AI Error:", error);
        toast.error("Failed to generate description. Please try again.");
    } finally {
        setIsAiLoading(false);
    }
  };

  const handleRefineSpec = async () => {
    const title = form.getValues("title");
    const priority = form.getValues("priority");
    const description = form.getValues("description");

    if (!title || title.length < 3) {
      toast.warning("Add a task title before asking AI to refine it.");
      return;
    }

    setIsAiLoading(true);
    try {
      const refined = await refineTaskSpec(title, description, priority, projectId);
      setLastRefinedSpec(refined);
      form.setValue("description", refined.markdown, {
        shouldValidate: true,
        shouldDirty: true,
      });
      toast.success(
        refined.source?.startsWith("fallback")
          ? "Spec refined with local fallback."
          : "Spec refined with AI."
      );
    } catch (error) {
      console.error("AI refine error:", error);
      toast.error("Could not refine the task spec.");
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleEstimateStoryPoints = async () => {
    if (!supportsStoryPoints) return;

    const title = form.getValues("title");
    const priority = form.getValues("priority");
    const description = form.getValues("description");

    if (!title || title.length < 3) {
      toast.warning("Add a task title before estimating story points.");
      return;
    }

    setIsEstimateLoading(true);
    try {
      const estimate = await estimateTaskStoryPoints(title, description, priority, projectId);
      setLastEstimate(estimate);
      form.setValue("story_points", String(estimate.story_points), {
        shouldValidate: true,
        shouldDirty: true,
      });
      toast.success(`AI estimate: ${estimate.story_points} story points`);
    } catch (error) {
      console.error("AI estimate error:", error);
      toast.error("Could not estimate story points.");
    } finally {
      setIsEstimateLoading(false);
    }
  };

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    try {
      const assigneeId = values.assignee_id && values.assignee_id !== "unassigned" 
        ? parseInt(values.assignee_id) 
        : undefined;
      const teamId = values.team_id && values.team_id !== "none"
        ? Number(values.team_id)
        : undefined;
      const storyPoints = supportsStoryPoints && values.story_points
        ? Number(values.story_points)
        : undefined;
      const dueDate = values.due_date ? `${values.due_date}T23:59:00` : undefined;

      const newTask = await createTask({
        title: values.title,
        description: values.description,
        priority: values.priority,
        story_points: storyPoints,
        due_date: dueDate,
        project_id: projectId,
        assignee_id: assigneeId, 
        team_id: teamId,
        sprint_id: sprintId,
        subtasks: createAiSubtasks
          ? (lastRefinedSpec?.suggested_subtasks || [])
              .map((item) => item.trim())
              .filter(Boolean)
              .slice(0, 20)
          : [],
      });
      
      onTaskCreated(newTask);
      toast.success("Task created successfully");
      setOpen(false);
      setLastEstimate(null);
      setLastRefinedSpec(null);
      form.reset();
    } catch (error) {
      console.error(error);
      toast.error("Failed to create task");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-blue-600 hover:bg-blue-700 shadow-lg shadow-blue-900/20">
            <Plus className="mr-2 h-4 w-4" /> Create Issue
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[550px] bg-slate-950 border-slate-800 text-slate-50">
        <DialogHeader>
          <DialogTitle>Create New Issue</DialogTitle>
          <DialogDescription className="text-slate-400">
            Define the task, assign it to a team member and estimate it when the methodology supports it.
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5 py-4">
            
            {/* ROW 1: Title */}
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Title</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. Implement Auth" {...field} className="bg-slate-900 border-slate-700 h-11" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* ROW 2: Priority, Estimation & Assignee */}
            <div className={supportsStoryPoints ? "grid grid-cols-1 gap-4 md:grid-cols-3" : "grid grid-cols-1 gap-4 md:grid-cols-2"}>
                <FormField
                  control={form.control}
                  name="priority"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Priority</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger className="bg-slate-900 border-slate-700 h-11">
                            <SelectValue placeholder="Select priority" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent className="bg-slate-900 border-slate-800 text-slate-200">
                          <SelectItem value={TaskPriority.LOW}>Low</SelectItem>
                          <SelectItem value={TaskPriority.MEDIUM}>Medium</SelectItem>
                          <SelectItem value={TaskPriority.HIGH}>High</SelectItem>
                          <SelectItem value={TaskPriority.CRITICAL}>Critical</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {supportsStoryPoints && (
                  <FormField
                    control={form.control}
                    name="story_points"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Story Points</FormLabel>
                        <FormControl>
                          <div className="relative">
                            <Gauge className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
                            <Input
                              type="number"
                              min="0"
                              max="100"
                              placeholder="0"
                              {...field}
                              className="h-11 border-slate-700 bg-slate-900 pl-9"
                            />
                          </div>
                        </FormControl>
                        <button
                          type="button"
                          onClick={handleEstimateStoryPoints}
                          disabled={isEstimateLoading || isLoading}
                          className="mt-2 inline-flex items-center text-xs text-blue-400 transition hover:text-blue-300 disabled:opacity-50"
                        >
                          {isEstimateLoading ? (
                            <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                          ) : (
                            <BadgeCheck className="mr-1 h-3 w-3" />
                          )}
                          Estimate
                        </button>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}

                <FormField
                  control={form.control}
                  name="assignee_id"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Assignee</FormLabel>
                      <Select onValueChange={field.onChange} defaultValue={field.value}>
                        <FormControl>
                          <SelectTrigger className="bg-slate-900 border-slate-700 h-11">
                             <div className="flex items-center gap-2">
                                <Users className="w-4 h-4 text-slate-400"/>
                                <SelectValue placeholder={loadingMembers ? "Loading..." : "Unassigned"} />
                             </div>
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent className="bg-slate-900 border-slate-800 text-slate-200">
                          <SelectItem value="unassigned" className="text-slate-400 italic">Unassigned</SelectItem>
                          {members.map((member) => (
                              <SelectItem key={member.membership_id} value={member.user.id.toString()}>
                                  <div className="flex items-center gap-2">
                                      <UserAvatar
                                        name={member.user.full_name}
                                        email={member.user.email}
                                        src={member.user.avatar_url}
                                        className="h-5 w-5"
                                        fallbackClassName="bg-blue-900 text-[9px] text-blue-100"
                                      />
                                      {member.user.full_name || member.user.email}
                                  </div>
                              </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
            </div>

            <FormField
              control={form.control}
              name="team_id"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Delivery Team</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger className="h-11 border-slate-700 bg-slate-900">
                        <SelectValue placeholder="No team" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent className="border-slate-800 bg-slate-900 text-slate-200">
                      <SelectItem value="none">No team</SelectItem>
                      {teams.map((team) => (
                        <SelectItem key={team.id} value={String(team.id)}>
                          {team.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="due_date"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Target Date</FormLabel>
                  <FormControl>
                    <Input
                      type="date"
                      {...field}
                      className="h-11 border-slate-700 bg-slate-900"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* ROW 3: Description cu buton AI funcțional */}
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex justify-between items-center">
                      Description
                      <div className="flex items-center gap-3">
                        <button
                          type="button"
                          onClick={handleGenerateAI}
                          disabled={isAiLoading}
                          className="text-xs text-blue-400 flex items-center cursor-pointer hover:text-blue-300 transition disabled:opacity-50"
                        >
                          {isAiLoading ? (
                              <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                          ) : (
                              <Sparkles className="w-3 h-3 mr-1" />
                          )}
                          {isAiLoading ? "Generating..." : "Generate with AI"}
                        </button>
                        <button
                          type="button"
                          onClick={handleRefineSpec}
                          disabled={isAiLoading}
                          className="text-xs text-emerald-400 flex items-center cursor-pointer hover:text-emerald-300 transition disabled:opacity-50"
                        >
                          {isAiLoading ? (
                            <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                          ) : (
                            <Sparkles className="w-3 h-3 mr-1" />
                          )}
                          Refine spec
                        </button>
                      </div>
                  </FormLabel>
                  <FormControl>
                    <Textarea 
                        placeholder="Add acceptance criteria and details..." 
                        className="bg-slate-900 border-slate-700 resize-none h-24" 
                        {...field} 
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {lastEstimate && supportsStoryPoints && (
              <div className="rounded-2xl border border-blue-500/20 bg-blue-500/10 p-3 text-xs text-blue-100">
                <div className="flex items-center justify-between gap-3">
                  <span className="font-semibold">
                    Estimate confidence: {lastEstimate.confidence}%
                  </span>
                  <span className="rounded-full border border-blue-400/30 px-2 py-0.5">
                    {lastEstimate.source || "ai"}
                  </span>
                </div>
                <p className="mt-2 leading-5 text-blue-100/80">
                  {lastEstimate.reasoning}
                </p>
              </div>
            )}

            {lastRefinedSpec?.suggested_subtasks?.length ? (
              <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-3">
                <div className="mb-3 flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2 text-sm font-semibold text-emerald-100">
                    <CheckCircle2 className="h-4 w-4 text-emerald-300" />
                    AI suggested checklist
                  </div>
                  <button
                    type="button"
                    onClick={() => setCreateAiSubtasks((value) => !value)}
                    className="rounded-full border border-emerald-400/30 px-2.5 py-1 text-xs text-emerald-100 transition hover:bg-emerald-500/10"
                  >
                    {createAiSubtasks ? "Will create subtasks" : "Text only"}
                  </button>
                </div>
                <div className="space-y-2">
                  {lastRefinedSpec.suggested_subtasks.slice(0, 6).map((subtask) => (
                    <div key={subtask} className="flex items-start gap-2 text-xs leading-5 text-emerald-50/85">
                      <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-300" />
                      <span>{subtask}</span>
                    </div>
                  ))}
                </div>
              </div>
            ) : null}

            <DialogFooter className="pt-2">
               <Button type="button" variant="ghost" onClick={() => setOpen(false)} className="text-slate-400 hover:text-white">Cancel</Button>
               <Button type="submit" className="bg-blue-600 hover:bg-blue-700 min-w-[120px]" disabled={isLoading}>
                 {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : "Create Issue"}
               </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
